name: Fetch RSS and Save to Pocket

on:
  schedule:
    - cron: '0 */6 * * *' # Runs every 6 hours
    # - cron: '0 * * * *' # Runs every hour

  workflow_dispatch: # Allows manual runs

jobs:
  fetch_and_save:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install feedparser requests

      - name: Run script
        env:
          POCKET_CONSUMER_KEY: ${{ secrets.POCKET_CONSUMER_KEY }}
          POCKET_ACCESS_TOKEN: ${{ secrets.POCKET_ACCESS_TOKEN }}
        run: python ./.github/scripts/rss-to-pocket.py
